name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Secret Key in Files
        run: |
          echo "const SECRET_KEY = '${{ secrets.SECRET_KEY }}';" > index.js
          echo "const SECRET_KEY = '${{ secrets.SECRET_KEY }}';" > link.js
          echo "const SECRET_KEY = '${{ secrets.SECRET_KEY }}';" > env.js

      - name: Ensure Deploy Directory
        run: |
          mkdir -p deploy

      - name: Copy Files to Deploy Directory
        run: |
          cp index.html deploy/index.html
          cp link.html deploy/link.html
          cp index.js deploy/index.js
          cp link.js deploy/link.js
          cp env.js deploy/env.js
          echo '{}' > deploy/.nojekyll  # Create .nojekyll file to disable Jekyll processing (if necessary)

      - name: Commit and Push Changes
        run: |
          cd deploy
          git init
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:gh-pages

